import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import { Bounce, ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Bounce}
        />
      <Script
                strategy="beforeInteractive"
                id="otpless-sdk"
                type="text/javascript"
                data-appid="40QPLY4PUSRV0E0VMZCU"
                src="https://otpless.com/v2/auth.js"
            />
    </html>
  );
}
